services:
  cosmosdb-nosql:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview
    restart: always
    ports:
      - "8081:8081"
      - "1234:1234"

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite@sha256:647c63a91102a9d8e8000aab803436e1fc85fbb285e7ce830a82ee5d6661cf37 # 3.34.0
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    command: azurite --location /data --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0
    volumes:
      - azurite:/data

volumes:
  azurite:
